In [1]:
import pandas as pd
df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,100,320]
})

In [ ]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    100
5     Paris    320

In [5]:
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price

{'London': 150.0, 'New York': 150.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [7]:
df['city_encoded']=df['city'].map(mean_price)

In [8]:
df

       city  price  city_encoded
0  New York    200         150.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    100         150.0
5     Paris    320         310.0

In [9]:
new_df=df[['city','city_encoded']]
new_df

       city  city_encoded
0  New York         150.0
1    London         150.0
2     Paris         310.0
3     Tokyo         250.0
4  New York         150.0
5     Paris         310.0